language: ruby
sudo: false

rvm:
  - 2.3.1

services:
  - mysql
  - redis-server

branches:
    only:
        - fahadiqbal1-development

script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
before_script:
  - cp .env.sample .env
  - mysql -e 'create database db_sm_test;'