# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48711f3765a1d02bd96efbb3d1aacb7ac1a0beabc650216f4b1151ea692b90c82f4e047ec5d83ce9ee1ed6c7f3db3166830e99fc9c940ba2b45fee75eb1660b7

test:
  secret_key_base: cc43bbbb972216e9a1944ce5b39cb38fa9dc2d4690ebb04a30873c981773fe199876ccb7b3c39ca61596ac54a76e4b2ee45680d11628b052071a6254d0f52d11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
