# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# LANGUAGES
Language.create!(name: 'English')
Language.create!(name: 'Français')
Language.create!(name: 'Deutsche')
Language.create!(name: 'العربية')

# COUNTRIES
Country.create!(name:'Afghanistan',iso_code:'AF',dial_code:93)
Country.create!(name:'Aland Islands',iso_code:'AX',dial_code:358)
Country.create!(name:'Albania',iso_code:'AL',dial_code:355)
Country.create!(name:'Algeria',iso_code:'DZ',dial_code:213)
Country.create!(name:'American Samoa',iso_code:'AS',dial_code:1)
Country.create!(name:'Andorra',iso_code:'AD',dial_code:376)
Country.create!(name:'Angola',iso_code:'AO',dial_code:244)
Country.create!(name:'Anguilla',iso_code:'AI',dial_code:1)
Country.create!(name:'Antarctica',iso_code:'AQ',dial_code:672)
Country.create!(name:'Argentina',iso_code:'AR',dial_code:54)
Country.create!(name:'Armenia',iso_code:'AM',dial_code:374)
Country.create!(name:'Aruba',iso_code:'AW',dial_code:297)
Country.create!(name:'Australia',iso_code:'AU',dial_code:61)
Country.create!(name:'Austria',iso_code:'AT',dial_code:43)
Country.create!(name:'Azerbaijan',iso_code:'AZ',dial_code:994)
Country.create!(name:'Bahamas',iso_code:'BS',dial_code:1)
Country.create!(name:'Bahrain',iso_code:'BH',dial_code:973)
Country.create!(name:'Bangladesh',iso_code:'BD',dial_code:880)
Country.create!(name:'Barbados',iso_code:'BB',dial_code:1)
Country.create!(name:'Belarus',iso_code:'BY',dial_code:375)
Country.create!(name:'Belgium',iso_code:'BE',dial_code:32)
Country.create!(name:'Belize',iso_code:'BZ',dial_code:501)
Country.create!(name:'Benin',iso_code:'BJ',dial_code:229)
Country.create!(name:'Bermuda',iso_code:'BM',dial_code:1)
Country.create!(name:'Bhutan',iso_code:'BT',dial_code:975)
Country.create!(name:'Bosnia and Herzegovina',iso_code:'BA',dial_code:387)
Country.create!(name:'Botswana',iso_code:'BW',dial_code:267)
Country.create!(name:'Bouvet Island',iso_code:'BV',dial_code:47)
Country.create!(name:'Brazil',iso_code:'BR',dial_code:55)
Country.create!(name:'Brunei Darussalam',iso_code:'BN',dial_code:673)
Country.create!(name:'Bulgaria',iso_code:'BG',dial_code:359)
Country.create!(name:'Burkina Faso',iso_code:'BF',dial_code:226)
Country.create!(name:'Burundi',iso_code:'BI',dial_code:257)
Country.create!(name:'Cambodia',iso_code:'KH',dial_code:855)
Country.create!(name:'Cameroon',iso_code:'CM',dial_code:237)
Country.create!(name:'Canada',iso_code:'CA',dial_code:1)
Country.create!(name:'Cape Verde',iso_code:'CV',dial_code:238)
Country.create!(name:'Cayman Islands',iso_code:'KY',dial_code:1)
Country.create!(name:'Central African Republic',iso_code:'CF',dial_code:236)
Country.create!(name:'Chad',iso_code:'TD',dial_code:235)
Country.create!(name:'Chile',iso_code:'CL',dial_code:56)
Country.create!(name:'China',iso_code:'CN',dial_code:86)
Country.create!(name:'Christmas Island',iso_code:'CX',dial_code:61)
Country.create!(name:'Cocos Keeling Islands',iso_code:'CC',dial_code:61)
Country.create!(name:'Colombia',iso_code:'CO',dial_code:57)
Country.create!(name:'Comoros',iso_code:'KM',dial_code:269)
Country.create!(name:'Congo',iso_code:'CG',dial_code:242)
Country.create!(name:'Cook Islands',iso_code:'CK',dial_code:682)
Country.create!(name:'Costa Rica',iso_code:'CR',dial_code:506)
Country.create!(name:'C?te d\'Ivoire',iso_code:'CI',dial_code:225)
Country.create!(name:'Croatia',iso_code:'HR',dial_code:385)
Country.create!(name:'Cuba',iso_code:'CU',dial_code:53)
Country.create!(name:'Cura?ao',iso_code:'CW',dial_code:599)
Country.create!(name:'Cyprus',iso_code:'CY',dial_code:357)
Country.create!(name:'Czech Republic',iso_code:'CZ',dial_code:420)
Country.create!(name:'Denmark',iso_code:'DK',dial_code:45)
Country.create!(name:'Djibouti',iso_code:'DJ',dial_code:253)
Country.create!(name:'Dominica',iso_code:'DM',dial_code:1)
Country.create!(name:'Dominican Republic',iso_code:'DO',dial_code:1)
Country.create!(name:'Ecuador',iso_code:'EC',dial_code:593)
Country.create!(name:'Egypt',iso_code:'EG',dial_code:20)
Country.create!(name:'El Salvador',iso_code:'SV',dial_code:503)
Country.create!(name:'Equatorial Guinea',iso_code:'GQ',dial_code:240)
Country.create!(name:'Eritrea',iso_code:'ER',dial_code:291)
Country.create!(name:'Estonia',iso_code:'EE',dial_code:372)
Country.create!(name:'Ethiopia',iso_code:'ET',dial_code:251)
Country.create!(name:'Faroe Islands',iso_code:'FO',dial_code:298)
Country.create!(name:'Fiji',iso_code:'FJ',dial_code:679)
Country.create!(name:'Finland',iso_code:'FI',dial_code:358)
Country.create!(name:'France',iso_code:'FR',dial_code:33)
Country.create!(name:'French Guiana',iso_code:'GF',dial_code:594)
Country.create!(name:'French Polynesia',iso_code:'PF',dial_code:689)
Country.create!(name:'Gabon',iso_code:'GA',dial_code:241)
Country.create!(name:'Gambia',iso_code:'GM',dial_code:220)
Country.create!(name:'Georgia',iso_code:'GE',dial_code:995)
Country.create!(name:'Germany',iso_code:'DE',dial_code:49)
Country.create!(name:'Ghana',iso_code:'GH',dial_code:233)
Country.create!(name:'Gibraltar',iso_code:'GI',dial_code:350)
Country.create!(name:'Greece',iso_code:'GR',dial_code:30)
Country.create!(name:'Greenland',iso_code:'GL',dial_code:299)
Country.create!(name:'Grenada',iso_code:'GD',dial_code:1)
Country.create!(name:'Guadeloupe',iso_code:'GP',dial_code:590)
Country.create!(name:'Guam',iso_code:'GU',dial_code:1)
Country.create!(name:'Guatemala',iso_code:'GT',dial_code:502)
Country.create!(name:'Guernsey',iso_code:'GG',dial_code:44)
Country.create!(name:'Guinea',iso_code:'GN',dial_code:224)
Country.create!(name:'Guinea-Bissau',iso_code:'GW',dial_code:245)
Country.create!(name:'Guyana',iso_code:'GY',dial_code:592)
Country.create!(name:'Haiti',iso_code:'HT',dial_code:509)
Country.create!(name:'Honduras',iso_code:'HN',dial_code:504)
Country.create!(name:'Hong Kong',iso_code:'HK',dial_code:852)
Country.create!(name:'Hungary',iso_code:'HU',dial_code:36)
Country.create!(name:'Iceland',iso_code:'IS',dial_code:354)
Country.create!(name:'India',iso_code:'IN',dial_code:91)
Country.create!(name:'Indonesia',iso_code:'ID',dial_code:62)
Country.create!(name:'Islamic Republic of Iran',iso_code:'IR',dial_code:98)
Country.create!(name:'Iraq',iso_code:'IQ',dial_code:964)
Country.create!(name:'Ireland',iso_code:'IE',dial_code:353)
Country.create!(name:'Isle of Man',iso_code:'IM',dial_code:44)
Country.create!(name:'Italy',iso_code:'IT',dial_code:39)
Country.create!(name:'Jamaica',iso_code:'JM',dial_code:1)
Country.create!(name:'Japan',iso_code:'JP',dial_code:81)
Country.create!(name:'Jersey',iso_code:'JE',dial_code:44)
Country.create!(name:'Jordan',iso_code:'JO',dial_code:962)
Country.create!(name:'Kazakhstan',iso_code:'KZ',dial_code:7)
Country.create!(name:'Kenya',iso_code:'KE',dial_code:254)
Country.create!(name:'Kiribati',iso_code:'KI',dial_code:686)
Country.create!(name:'Kuwait',iso_code:'KW',dial_code:965)
Country.create!(name:'Kyrgyzstan',iso_code:'KG',dial_code:996)
Country.create!(name:'Latvia',iso_code:'LV',dial_code:371)
Country.create!(name:'Lebanon',iso_code:'LB',dial_code:961)
Country.create!(name:'Lesotho',iso_code:'LS',dial_code:266)
Country.create!(name:'Liberia',iso_code:'LR',dial_code:231)
Country.create!(name:'Libya',iso_code:'LY',dial_code:218)
Country.create!(name:'Liechtenstein',iso_code:'LI',dial_code:423)
Country.create!(name:'Lithuania',iso_code:'LT',dial_code:370)
Country.create!(name:'Luxembourg',iso_code:'LU',dial_code:352)
Country.create!(name:'Macao',iso_code:'MO',dial_code:853)
Country.create!(name:'Macedonia',iso_code:'MK',dial_code:389)
Country.create!(name:'Madagascar',iso_code:'MG',dial_code:261)
Country.create!(name:'Malawi',iso_code:'MW',dial_code:265)
Country.create!(name:'Malaysia',iso_code:'MY',dial_code:60)
Country.create!(name:'Maldives',iso_code:'MV',dial_code:960)
Country.create!(name:'Mali',iso_code:'ML',dial_code:223)
Country.create!(name:'Malta',iso_code:'MT',dial_code:356)
Country.create!(name:'Marshall Islands',iso_code:'MH',dial_code:692)
Country.create!(name:'Martinique',iso_code:'MQ',dial_code:596)
Country.create!(name:'Mauritania',iso_code:'MR',dial_code:222)
Country.create!(name:'Mauritius',iso_code:'MU',dial_code:230)
Country.create!(name:'Mayotte',iso_code:'YT',dial_code:262)
Country.create!(name:'Mexico',iso_code:'MX',dial_code:52)
Country.create!(name:'Republic of Moldova',iso_code:'MD',dial_code:373)
Country.create!(name:'Monaco',iso_code:'MC',dial_code:377)
Country.create!(name:'Mongolia',iso_code:'MN',dial_code:976)
Country.create!(name:'Montenegro',iso_code:'ME',dial_code:382)
Country.create!(name:'Montserrat',iso_code:'MS',dial_code:1)
Country.create!(name:'Morocco',iso_code:'MA',dial_code:212)
Country.create!(name:'Mozambique',iso_code:'MZ',dial_code:258)
Country.create!(name:'Myanmar',iso_code:'MM',dial_code:95)
Country.create!(name:'Namibia',iso_code:'NA',dial_code:264)
Country.create!(name:'Nauru',iso_code:'NR',dial_code:674)
Country.create!(name:'Nepal',iso_code:'NP',dial_code:977)
Country.create!(name:'Netherlands',iso_code:'NL',dial_code:31)
Country.create!(name:'New Caledonia',iso_code:'NC',dial_code:687)
Country.create!(name:'New Zealand',iso_code:'NZ',dial_code:64)
Country.create!(name:'Nicaragua',iso_code:'NI',dial_code:505)
Country.create!(name:'Niger',iso_code:'NE',dial_code:227)
Country.create!(name:'Nigeria',iso_code:'NG',dial_code:234)
Country.create!(name:'Niue',iso_code:'NU',dial_code:683)
Country.create!(name:'Norfolk Island',iso_code:'NF',dial_code:672)
Country.create!(name:'Norway',iso_code:'NO',dial_code:47)
Country.create!(name:'Oman',iso_code:'OM',dial_code:968)
Country.create!(name:'Pakistan',iso_code:'PK',dial_code:92)
Country.create!(name:'Palau',iso_code:'PW',dial_code:680)
Country.create!(name:'State of Palestine',iso_code:'PS',dial_code:970)
Country.create!(name:'Panama',iso_code:'PA',dial_code:507)
Country.create!(name:'Papua New Guinea',iso_code:'PG',dial_code:675)
Country.create!(name:'Paraguay',iso_code:'PY',dial_code:595)
Country.create!(name:'Peru',iso_code:'PE',dial_code:51)
Country.create!(name:'Philippines',iso_code:'PH',dial_code:63)
Country.create!(name:'Pitcairn',iso_code:'PN',dial_code:870)
Country.create!(name:'Poland',iso_code:'PL',dial_code:48)
Country.create!(name:'Portugal',iso_code:'PT',dial_code:351)
Country.create!(name:'Puerto Rico',iso_code:'PR',dial_code:1)
Country.create!(name:'Qatar',iso_code:'QA',dial_code:974)
Country.create!(name:'Romania',iso_code:'RO',dial_code:40)
Country.create!(name:'Russian Federation',iso_code:'RU',dial_code:7)
Country.create!(name:'Rwanda',iso_code:'RW',dial_code:250)
Country.create!(name:'R?union',iso_code:'RE',dial_code:262)
Country.create!(name:'Saint Barth?lemy',iso_code:'BL',dial_code:590)
Country.create!(name:'Saint Kitts and Nevis',iso_code:'KN',dial_code:1)
Country.create!(name:'Saint Lucia',iso_code:'LC',dial_code:1)
Country.create!(name:'Saint Martin French part',iso_code:'MF',dial_code:590)
Country.create!(name:'Saint Pierre and Miquelon',iso_code:'PM',dial_code:508)
Country.create!(name:'Saint Vincent and the Grenadines',iso_code:'VC',dial_code:1)
Country.create!(name:'Samoa',iso_code:'WS',dial_code:685)
Country.create!(name:'San Marino',iso_code:'SM',dial_code:378)
Country.create!(name:'Sao Tome and Principe',iso_code:'ST',dial_code:239)
Country.create!(name:'Saudi Arabia',iso_code:'SA',dial_code:966)
Country.create!(name:'Senegal',iso_code:'SN',dial_code:221)
Country.create!(name:'Serbia',iso_code:'RS',dial_code:381)
Country.create!(name:'Seychelles',iso_code:'SC',dial_code:248)
Country.create!(name:'Sierra Leone',iso_code:'SL',dial_code:232)
Country.create!(name:'Singapore',iso_code:'SG',dial_code:65)
Country.create!(name:'Slovakia',iso_code:'SK',dial_code:421)
Country.create!(name:'Slovenia',iso_code:'SI',dial_code:386)
Country.create!(name:'Solomon Islands',iso_code:'SB',dial_code:677)
Country.create!(name:'Somalia',iso_code:'SO',dial_code:252)
Country.create!(name:'South Africa',iso_code:'ZA',dial_code:27)
Country.create!(name:'South Sudan',iso_code:'SS',dial_code:211)
Country.create!(name:'Spain',iso_code:'ES',dial_code:34)
Country.create!(name:'Sri Lanka',iso_code:'LK',dial_code:94)
Country.create!(name:'Sudan',iso_code:'SD',dial_code:249)
Country.create!(name:'Suriname',iso_code:'SR',dial_code:597)
Country.create!(name:'Svalbard and Jan Mayen',iso_code:'SJ',dial_code:47)
Country.create!(name:'Swaziland',iso_code:'SZ',dial_code:268)
Country.create!(name:'Sweden',iso_code:'SE',dial_code:46)
Country.create!(name:'Switzerland',iso_code:'CH',dial_code:41)
Country.create!(name:'Syrian Arab Republic',iso_code:'SY',dial_code:963)
Country.create!(name:'Taiwan',iso_code:'TW',dial_code:886)
Country.create!(name:'Tajikistan',iso_code:'TJ',dial_code:992)
Country.create!(name:'Tanzania',iso_code:'TZ',dial_code:255)
Country.create!(name:'Thailand',iso_code:'TH',dial_code:66)
Country.create!(name:'Timor-Leste',iso_code:'TL',dial_code:670)
Country.create!(name:'Togo',iso_code:'TG',dial_code:228)
Country.create!(name:'Tokelau',iso_code:'TK',dial_code:690)
Country.create!(name:'Tonga',iso_code:'TO',dial_code:676)
Country.create!(name:'Trinidad and Tobago',iso_code:'TT',dial_code:1)
Country.create!(name:'Tunisia',iso_code:'TN',dial_code:216)
Country.create!(name:'Turkey',iso_code:'TR',dial_code:90)
Country.create!(name:'Turkmenistan',iso_code:'TM',dial_code:993)
Country.create!(name:'Tuvalu',iso_code:'TV',dial_code:688)
Country.create!(name:'Uganda',iso_code:'UG',dial_code:256)
Country.create!(name:'Ukraine',iso_code:'UA',dial_code:380)
Country.create!(name:'United Arab Emirates',iso_code:'AE',dial_code:971)
Country.create!(name:'United Kingdom',iso_code:'GB',dial_code:44)
Country.create!(name:'United States',iso_code:'US',dial_code:1)
Country.create!(name:'Uruguay',iso_code:'UY',dial_code:598)
Country.create!(name:'Uzbekistan',iso_code:'UZ',dial_code:998)
Country.create!(name:'Vanuatu',iso_code:'VU',dial_code:678)
Country.create!(name:'Venezuela',iso_code:'VE',dial_code:58)
Country.create!(name:'Viet Nam',iso_code:'VN',dial_code:84)
Country.create!(name:'Wallis and Futuna',iso_code:'WF',dial_code:681)
Country.create!(name:'Western Sahara',iso_code:'EH',dial_code:212)
Country.create!(name:'Yemen',iso_code:'YE',dial_code:967)
Country.create!(name:'Zambia',iso_code:'ZM',dial_code:260)
Country.create!(name:'Zimbabwe',iso_code:'ZW',dial_code:263)


# ADMIN
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password', role: 'admin')
AdminUser.create!(email: 'superuser@example.com', password: 'password', password_confirmation: 'password', role: 'superuser')
AdminUser.create!(email: 'courseuser@example.com', password: 'password', password_confirmation: 'password', role: 'courseuser')
AdminUser.create!(email: 'translator@example.com', password: 'password', password_confirmation: 'password', role: 'translator')
AdminUser.create!(email: 'user@example.com', password: 'password', password_confirmation: 'password', role: 'user')

# GENDER
Gender.create!(gender: "Male")
Gender.create!(gender: "Female")
Gender.create!(gender: "N/A")

# MESSAGE SERVICES
MessageService.create!(service: "email")
MessageService.create!(service: "SMS")